version: '3'

services:
  lighttpd:
    image: sebp/lighttpd:latest
    depends_on:
     - php-fpm
    volumes:
     - .:/var/www/platform
     - ./docker/lighttpd.conf:/etc/lighttpd/lighttpd.conf:ro
    ports:
     - "50080:80"

  php-fpm:
    image: dugwood/phalcon-php-fpm:3.4.1
    volumes:
     - .:/var/www/platform
    working_dir: /var/www/platform
    ports:
     - "9000:9000"

  db:
    image: percona/percona-xtradb-cluster:5.6
    restart: always
    volumes:
     - .:/var/www/platform
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: PARITER
      CLUSTER_NAME: pariter-pxc
    ports:
     - "53306:3306"
